#twig:
#    default_path: '%kernel.project_dir%/templates'
#    globals:
#        categoriesVar: '@App\Twig\GlobalsVar'
#
#when@test:
#    twig:
#        strict_variables: true

twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        categoriesVar: '@App\Twig\GlobalsVar'


when@test:
    twig:
        strict_variables: true